### PR TITLE
create code of conduct on the covid-19-bh20 repository

### PR DESCRIPTION
**Pull request by malvikasharan**
## Summary

- Adding a dedicated Code of Conduct for this event/group

## Where can the project lead help

- Please add a few members as designated CoC report taker and responders

## Reference:

- TODO group
- Taken directly from one of the project I am a co-founder of https://openlifesci.org/

### CODE REVIEW

**Comment by rvosa** [comment]
This looks good to me. I guess we need a CoC contact person?

**Comment by uniqueg** [comment]
Does the CoC response team have to be different from the coordinating team? Because as it is now, it's clearly [stated on the front page](https://github.com/virtual-biohackathons/covid-19-bh20#code-of-conduct) of the repo that any CoC concerns/issues should be sent to them.

**Comment by peterjc** [comment]
For background to the ``CODE_OF_CONDUCT.md`` file naming, see https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

This proposed CoC is different from the current one listed in the main README, a link to https://fosdem.org/2020/practical/conduct/ - so the README would also need updating to point at the new file.

Alternatively, the new ``CODE_OF_CONDUCT.md`` file could contain a copy of the FOSDEM 2020 CoC (with a link to the original). However personally I don't see that as a good fit, given how it is tied to a physical in person conference.

**Comment by pjotrp** [comment]
Thanks. Yes, please update the README too.

**Comment by malvikasharan** [comment]
Thanks @ljgarcia for updating the README. Can you please add your name instead of organisers? That will give people a little bit of confidence that their report will be handled by a person who they can trust for anonymity and support. You can work on this PR: https://github.com/virtual-biohackathons/covid-19-bh20/pull/4 (open)

**Pull request merged**
