### PR TITLE
Add section about biohackathon.curii.com Arvados instance

### PR DESCRIPTION
**Pull request by tetron**

### CODE REVIEW

**Comment by tetron** [comment]
oops hold on a sec I need to fix formatting

**Comment by tetron** [comment]
Actually, I don't think this is quite ready to be added to the main page, will reopen when it is ready.

**Review by heuermh — APPROVED** [review]
Thank you, @tetron!

**Comment by inutano** [comment]
Thanks @tetron and @heuermh !!

**Pull request merged**
